---
title: "Create a file and push to synapse with povenance"
description: "This file pulls data from synapse explore data and push plots back to Synapse "
author: "Thanneer Perumal"
date: "`r date()`"
output: html_document
---
## Setup
```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## It is assumed your working directory is where this file is

# Clear R console screen output
cat("\014")  

# Load required libraries
library(data.table)
library(plyr)
library(tidyverse)
library(ggplot2)
library(synapser)
library(knit2synapse)
library(githubr)

synLogin()

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = FALSE)
```

## Get data from synapse
```{r get.data, include = F}
COV_ID = 'syn8466814'
COV_OBJ = synGet(COV_ID)
COVAR = fread(COV_OBJ$path, data.table=F) 

COUNT_ID = 'syn8466816'
COUNT_OBJ = synGet(COUNT_ID)
COUNT = fread(COUNT_OBJ$path, data.table=F)
```
Covariates data obtained from `r COV_OBJ$properties$id` and counts data obtained from `r COUNT_OBJ$properties$id`

## Explore data
### Summarise number and category of samples
```{r explore1, eval = T}
COV = tidyr::separate(COVAR, Tissue.Diagnosis, c('Tissue','Diagnosis'), sep = '\\.')

table(COV$Tissue, COV$Diagnosis)
```
### Summarise covariates
```{r explore2, fig.width=12, fig.height=4}
# RIN
p = list()
p[[1]] = ggplot(COV, aes(x = Diagnosis, y = RIN)) + geom_boxplot()
p[[1]] = p[[1]] + ggtitle('RIN') + theme(legend.position = 'top')

# AgeAtDeath
p[[2]] = ggplot(COV, aes(x = Diagnosis, y = AgeAtDeath)) + geom_boxplot()
p[[2]] = p[[2]] + ggtitle('Age At Death') + theme(legend.position = 'top')

# PMI
p[[3]] = ggplot(COV, aes(x = Diagnosis, y = PMI)) + geom_boxplot()
p[[3]] = p[[3]] + ggtitle('PMI') + theme(legend.position = 'top')

ggpubr::ggarrange(plotlist = p, ncol = 3)
```


### Store results in synapse
```{r synapsestore, echo=FALSE, include=FALSE, cache=FALSE}
## Get commits from github
thisFileName <- 'push2yn.Rmd'
thisRepo <- getRepo('th1vairam/SageBrownBagDemo', ref='branch', refName='master')
thisFile <- getPermlink(repository = thisRepo,
                        repositoryPath=thisFileName)

# Store file with provenance in synapse
CODE <- synapser::File(path = thisFileName,
                       name = "Data Exploration",
                       parent = 'syn19113441') 
                       
CODE <- synapser::synStore(CODE,
                           activityName = 'Data exploration',
                           used = c(COV_ID, COUNT_ID),
                           executed = thisFile)
```

## Knit the markdown, create a folder entity and create the wiki
```{r create.file.in.synapse, include=FALSE, eval = FALSE}
createAndKnitToFileEntity(file = "./push2yn.Rmd", # Markdown file name
                          parentId = "syn19113441", # parentId to store this file in synapse
                          fileName = "Data Exploration") # optional fileName
```